config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  root to: 'pages#home'
  resources :movies do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# == Schema Information
#
# Table name: bookmarks
#
#  id         :bigint           not null, primary key
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  list_id    :bigint           not null
#  movie_id   :bigint           not null
#
# Indexes
#
#  index_bookmarks_on_list_id   (list_id)
#  index_bookmarks_on_movie_id  (movie_id)
#
# Foreign Keys
#
#  fk_rails_...  (list_id => lists.id)
#  fk_rails_...  (movie_id => movies.id)
#
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_presence_of :comment
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: [:list]
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class List < ApplicationRecord
  validates_uniqueness_of :name
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id         :bigint           not null, primary key
#  rating     :float
#  synopsis   :text
#  title      :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Movie < ApplicationRecord
  has_one_attached :poster
  validates_uniqueness_of :title, scope: [:synopsis]
  validates :rating, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 10
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new; end

  def create
    if params[:movie_id].present?
      @bookmark = Bookmark.new(bookmark_params)
      @movie = Movie.find(params[:movie_id])
      @bookmark.movie = @movie
      if @bookmark.save
        flash[:notice] = 'Successfully added to list.'
        redirect_to @bookmark.movie

      else
        @lists = List.all
        flash.now[:alert] = 'Unable to add to list.'
        render 'movies/show', status: :unprocessable_entity

      end

    elsif params[:list_id].present?
      @list = List.find(params[:list_id])
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.list = @list
      if @bookmark.save
        flash[:notice] = 'Successfully added to list.'
        redirect_to @bookmark.list

        # redirect_to list_path(@bookmark.list)
      else
        puts @bookmark.errors.messages
        @lists = List.all
        flash.now[:alert] = 'Unable to add to list.'
        render 'lists/show', status: :unprocessable_entity
        # render 'lists/show', status: 422
      end
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_bookmark; end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :list, :movie, :comment)
  end
end

# = form_with model: [@movie, @bookmark]

# { "bookmark" => { list_id: 1 }}

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show; end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit; end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = 'List successfully deleted.'
      redirect_to @list

    else
      flash.now[:alert] = 'Unable to update list'
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    if @list.update(list_params)
      flash[:notice] = 'List successfully updated.'
      redirect_to @list
    else
      flash.now[:alert] = 'Unable to update list'
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    flash[:notice] = 'List successfully deleted.'
    redirect_to lists_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to lists_path
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @lists = List.all
    @bookmark = Bookmark.new
    @movie = Movie.find(params[:id])

    # Add the bookmark new route here to create a form to add the movie to a list on the show page
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/delete.html.erb
<h1>Bookmarks#delete</h1>
<p>Find me in app/views/bookmarks/delete.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watchlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
  </head>
  <body id="vue">
    <div class="flex flex-col h-screen">
      <%= render "shared/navbar" %>
      <% flash.each do |type, msg| %>
        <%= render 'shared/flash', type: type, msg: msg %>
      <% end %>
      <main class="container flex-1 mx-auto px-5 flex flex-col ">
        <%= yield %>
      </main>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/lists/_empty_list_card.erb
<li class="relative">
  <div class="group aspect-w-10 aspect-h-7 block w-full top-black overflow-hidden rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 focus-within:ring-offset-gray-100">
    <img src="https://images.unsplash.com/photo-1616530940355-351fabd9524b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80" alt="Collection of movie poster" class="pointer-events-none object-cover group-hover:opacity-75" style="max-height: 420px;">
    <h3 class="mt-6 text-lg font-semibold text-gray-900">Go make a new list!</h3>
  </div>
</li>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
<%= render "shared/error_messages", resource: form.object %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<li id="<%= dom_id list %>" class="relative">
  <div class="group aspect-w-10 aspect-h-7 block w-full top-black overflow-hidden rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 focus-within:ring-offset-gray-100">
    <h2 class="my-5">
      <%= list.name %>
    </h2>
    <img src="<%= list.movies.first.url %>" alt="List thumbnail" class="pointer-events-none mb-6 object-cover group-hover:opacity-75" style="max-height: 420px;">
    <% if action_name != "show" %>
      <%= link_to 'Edit this list', edit_list_path(list), class: "text-center w-full btn btn-secondary" %>
      <%= button_to 'Delete this list', list, method: :delete, class: "w-full btn btn-danger" %>
      <hr class="mt-6">
      <p class="mt-1 text-sm text-gray-600 text"><%= list.bookmarks.length %> movies in this list</p>
    <% end %>
  </li>

app/views/lists/edit.html.erb
<div class="mx-auto sm:w-9/12 md:w-6/12 w-full">
  <h1 class="font-bold text-4xl">Editing <%= @list.name %></h1>
  <%= render "form", list: @list %>
  <hr class="my-8">
  <%= link_to "Show this list", @list, class: "btn btn-secondary" %>
  <%= link_to "Back to lists", lists_path, class: "btn btn-secondary" %>
</div>

app/views/lists/index.html.erb
<h1 class="pb-10 text-6xl align-text-top">My Lists</h1>
<div>
  <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% if @lists.length > 0 %>
      <% @lists.each do |list| %>
        <%= link_to list_path(list) do %>
          <%= render 'list', list: list %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_list_path do %>
        <%= render 'empty_list_card' %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="mx-auto sm:w-9/12 md:w-6/12 w-full">
  <h1 class="font-bold text-4xl">New list</h1>

  <%= render "form", list: @list %>
  <hr class="my-8">
  <%= link_to 'Back to lists', lists_path, class: "btn btn-secondary" %>
</div>

app/views/lists/show.html.erb
<!-- ><div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @list %>
    <hr class="my-4">
    <div class="flex justify-between items-center space-x-4">
      <%= link_to 'Edit this list', edit_list_path(@list), class: "btn btn-primary" %>
      <%= button_to 'Destroy this list', list_path(@list), method: :delete, class: "btn btn-secondary" %>
      <%= link_to 'Back to lists', lists_path, class: "btn btn-danger" %>
    </div>
  </div>
</div>
-->
<h1 class="pb-10 text-6xl align-text-top"><%= @list.name %></h1>
<div>
  <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% if @list.bookmarks.length > 0 %>
      <% @list.bookmarks.each do |bookmark| %>
        <div>
          <%= link_to movie_path(bookmark.movie) do %>
            <%= render 'movies/movie_card', movie: bookmark.movie %>
          <% end %>
          <%= button_to 'Remove from list', bookmark_path(bookmark), method: :delete, class:"flex w-full opacity-70 justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2" %>
        </div>
      <% end %>
    <% else %>
      <%= link_to movies_path do %>
        <%= render 'movies/empty_movie_card' %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/movies/_empty_movie_card.erb
<li class="relative">
  <div class="group aspect-w-10 aspect-h-7 block w-full top-black overflow-hidden rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 focus-within:ring-offset-gray-100">
    <img src="https://images.unsplash.com/photo-1616530940355-351fabd9524b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80" alt="Collection of movie poster" class="pointer-events-none object-cover group-hover:opacity-75" style="max-height: 420px;">
    <h3 class="mt-6 text-lg font-semibold text-gray-900">Go add a movie to your list!</h3>
  </div>
</li>

app/views/movies/_movie_card.html.erb
<li class="relative">
  <div class="group aspect-w-10 aspect-h-7 block w-full top-black overflow-hidden rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 focus-within:ring-offset-gray-100">
    <img src="<%= movie.url %>" alt="<%= movie.title %>'s Poster" class="pointer-events-none object-cover group-hover:opacity-75" style="max-height: 420px;">
    <button type="button" class="absolute inset-0 focus:outline-none">
      <span class="sr-only">View details for <%= movie.title %></span>
    </button>
    <h3 class="mt-6 text-lg font-semibold text-gray-900"><%= movie.title.truncate(32) %></h3>
    <p class="mt-1 text-sm text-gray-600"><%= movie.synopsis.truncate(80) %></p>
  </div>
</li>

app/views/movies/index.html.erb
<h1 class="pb-10 text-6xl align-text-top">Popular Movies</h1>
<div>
  <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% if @movies.length > 0 %>
      <% @movies.each do |movie| %>
        <%= link_to movie_path(movie) do %>
          <%= render 'movie_card', movie: movie %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to movies_path do %>
        <%= render 'empty_movie_card', movie: movie %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="relative bg-gray-50">
  <main class="lg:relative">
    <div class="mx-auto w-full max-w-7xl pt-16 pb-20 text-center lg:py-48 lg:text-left">
      <div class="px-4 sm:px-8 lg:w-1/2 xl:pr-16">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl lg:text-5xl xl:text-6xl">
          <span class="block xl:inline">You be the director with</span>
          <span class="block text-blue-600 xl:inline"> Watchlist</span>
        </h1>
        <p class="mx-auto mt-3 max-w-md text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">Search for your favourite movies and created curated lists, from what to watch next to groups of your all time favourites!</p>
        <div class="mt-10 sm:flex sm:justify-center lg:justify-start">
          <div class="rounded-md shadow">
            <%= link_to "Start a new list!", '#', class: "flex w-full items-center justify-center rounded-md border border-transparent bg-blue-600 px-8 py-3 text-base font-medium text-white hover:bg-blue-700 md:py-4 md:px-10 md:text-lg" %>
          </div>
          <div class="mt-3 rounded-md shadow sm:mt-0 sm:ml-3">
            <%= link_to 'Popular Movies', movies_path, class: "flex w-full items-center justify-center rounded-md border border-transparent bg-white px-8 py-3 text-base font-medium text-blue-600 hover:bg-gray-50 md:py-4 md:px-10 md:text-lg"%>
          </div>
        </div>
      </div>
    </div>
    <div class="relative h-64 w-full sm:h-72 md:h-96 lg:absolute lg:inset-y-0 lg:right-0 lg:h-full lg:w-1/2">
      <img class="absolute inset-0 h-full w-full object-cover" src="https://images.unsplash.com/photo-1520333789090-1afc82db536a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2102&q=80" alt="">
    </div>
  </main>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="bg-red-50 p-4 rounded mt-2 mb-6" role="alert">
    <div class="flex items-start justify-start">
      <div class="w-10 mr-4">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="fill-current icon mr-4 mt-1 flex-no-shrink" role="img" aria-labelledby="f1yx75u7nv0lvn6ck4z10w7lksjmk2f"><title id="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">Icons/close outline</title><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm1.41-1.41A8 8 0 1 0 15.66 4.34 8 8 0 0 0 4.34 15.66zm9.9-8.49L11.41 10l2.83 2.83-1.41 1.41L10 11.41l-2.83 2.83-1.41-1.41L8.59 10 5.76 7.17l1.41-1.41L10 8.59l2.83-2.83 1.41 1.41z"></path></svg>
      </div>
      <div>
        <h4 class="font-black text-sm uppercase mb-2">
          <%= pluralize(resource.errors.count, "error") %> prohibited this article from being saved:
        </h4>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li class="text-red-600"><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if type == 'notice' %>
  <div class="rounded-md bg-green-50 p-4">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: mini/check-circle -->
        <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium text-green-800"><%= msg %></p>
      </div>
      <div class="ml-auto pl-3">
        <div class="-mx-1.5 -my-1.5">
          <button type="button" class="inline-flex rounded-md bg-green-50 p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:ring-2 focus:ring-green-600 focus:ring-offset-2 focus:ring-offset-green-50">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: mini/x-mark -->
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% elsif type == 'alert' %>
  <div class="rounded-md bg-red-50 p-4">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: mini/check-circle -->
        <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M8.485 3.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 3.495zM10 6a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 6zm0 9a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium text-red-800"><%= msg %></p>
      </div>
      <div class="ml-auto pl-3">
        <div class="-mx-1.5 -my-1.5">
          <button type="button" class="inline-flex rounded-md bg-red-50 p-1.5 text-red-500 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-600 focus:ring-offset-2 focus:ring-offset-red-50">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: mini/x-mark -->
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="p-8 bg-gray-100">
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 justify-between">
      <div class="flex">
        <div class="-ml-2 mr-2 flex items-center md:hidden">
          <!-- Mobile menu button -->
          <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <!--
              Icon when menu is closed.

              Heroicon name: outline/bars-3

              Menu open: "hidden", Menu closed: "block"
            -->
            <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            <!--
              Icon when menu is open.

              Heroicon name: outline/x-mark

              Menu open: "block", Menu closed: "hidden"
            -->
            <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="flex flex-shrink-0 items-center">
          <%= link_to root_path do %>
            <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=blue&shade=500" alt="Your Company">
            <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=blue&shade=500" alt="Your Company">
          <% end %>
        </div>
        <div class="hidden md:ml-6 md:flex md:items-center md:space-x-4">
          <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
          <%= link_to "Popular Movies", movies_path, class: "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium", aria: { current: 'page'} %>
          <%= link_to "My Lists", lists_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <%= link_to "New List", new_list_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <%= link_to "Browse Movies", movies_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
        </div>
      </div>
    </div>
  </div>
</nav>